"""add wallet table

Revision ID: 0eb9d6350285
Revises:
Create Date: 2025-07-10 11:47:28.028855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0eb9d6350285"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "balance", sa.DECIMAL(precision=12, scale=2), nullable=False
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_wallets")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallets")
    # ### end Alembic commands ###
