services:
  wallets:
    build:
      context: ..
      dockerfile: ./compose/dockerfiles/app.Dockerfile
    container_name: wallets-app
    restart: always
    command: bash entrypoint.sh uvicorn src.main:app --host 0.0.0.0 --port ${APP__APPLICATION_PORT:-8000}
    depends_on:
      - postgres
