services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: "boilerplate-fastapi"
    command: bash entrypoint.sh uvicorn src.main:app --host 0.0.0.0 --port ${APP__APPLICATION_PORT:-8000} --reload
    depends_on:
      - postgres
