services:
  nginx:
    build:
      context: ..
      dockerfile: /compose/dockerfiles/nginx.Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    depends_on:
      - app
      - postgres
