services:
  nginx:
    build:
      context: ..
      dockerfile: ./compose/dockerfiles/nginx.Dockerfile
    container_name: wallets-nginx
    restart: always
    ports:
      - 8000:80
    depends_on:
      - wallets
      - postgres
